### ISSUE TITLE
(../packages/livewire-components) repository does not exist

### ISSUE THREAD

**Issue by Amadaus684** [lakasir/lakasir#109]
when execute git clone https://github.com/lakasir/lakasir.git  then cd lakasir than composer update, it says: [RuntimeException]
  The `url` supplied for the path (../packages/livewire-components) repository does not exist

**Comment by N34R** [comment]
Did you clone this repo? 
Try use `composer create-project lakasir/lakasir your-project-name`.
after that, run `composer install`

**Comment by Amadaus684** [comment]
> 

if i use it, it will say: 

[InvalidArgumentException]
  Could not find package lakasir/lakasir with stability stable.

**Comment by Amadaus684** [comment]
> > 
> 
> if i use it, it will say:
> 
> [InvalidArgumentException] Could not find package lakasir/lakasir with stability stable.

hh

**Comment by Amadaus684** [comment]
> Did you clone this repo? Try use `composer create-project lakasir/lakasir your-project-name`. after that, run `composer install`

if i use it, it will say:

[InvalidArgumentException]
Could not find package lakasir/lakasir with stability stable.

**Comment by Amadaus684** [comment]
> Did you clone this repo? Try use `composer create-project lakasir/lakasir your-project-name`. after that, run `composer install`

like my issue before: https://github.com/lakasir/lakasir/issues/108

**Comment by N34R** [comment]
This repo, still under development again. Thanks.

**Comment by sheenazien8** [comment]
thanks @N34R @Amadaus684
