### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by Fzoltan87** [lakasir/lakasir#140]
Hi, can you provide an installation guide for the system?

**Comment by Fzoltan87** [comment]
Yes, that's what I meant. Or maybe localhost.

**Comment by Fzoltan87** [comment]
I would need the installation steps step by step.

I did it like this:
- .env file configuration
- composer install
- npm install
- npm run dev
- php artisan key:generate
- php artisan migrate
- php artisan db:seed

Then I got an error here:

  Database\Seeders\UserSeeder .............................................................................................................. RUNNING  

   ErrorException 

  Attempt to read property "user" on null at database\seeders\UserSeeder.php:25

```
     21▕         $dbName = DB::connection()->getDatabaseName();
     22▕         $tenant = Tenant::find(Str::after($dbName, 'lakasir_')) ?? tenant();
     23▕ 
     24▕         User::create([
  ➜  25▕             'email' => $tenant->user->email,
     26▕             'password' => $tenant->user->password,
     27▕         ]);
     28▕     }
     29▕ }

  1   database\seeders\UserSeeder.php:25
      Illuminate\Foundation\Bootstrap\HandleExceptions::Illuminate\Foundation\Bootstrap\{closure}("Attempt to read property "user" on null", "C:\xampp\htdocs\lakasir-master\database\seeders\UserSeeder.php")

  2   vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:36
      Database\Seeders\UserSeeder::run()
```

**Comment by sheenazien8** [comment]
you must run php artisan tenant:migrate then tenant:seed @Fzoltan87

**Comment by sheenazien8** [comment]
Will update the installation guide soon

**Comment by Fzoltan87** [comment]
Thank you for completing the installation guide. This way, the project has already been installed.

However, the login doesn't work for me.

You can see the login data in the users table.

I open the following link: http://test.localhost:8000/member/login

You enter the data, but nothing happens, I don't even get an error message.

**Comment by sheenazien8** [comment]
Did you use valet or herd? I'll try to reproduce that's case in my local

**Comment by sheenazien8** [comment]
> ![Sad](https://private-user-images.githubusercontent.com/12618220/316668837-94f7da7d-92e0-4392-a573-048bc52eaaf4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MDk0NzksIm5iZiI6MTcxMTQwOTE3OSwicGF0aCI6Ii8xMjYxODIyMC8zMTY2Njg4MzctOTRmN2RhN2QtOTJlMC00MzkyLWE1NzMtMDQ4YmM1MmVhYWY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDIzMjYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYTQzYmRmZjVlZDY5OWYzMDA2NzY1ZGE4ZmI3ZTNkNWMzZjU3YTE1N2YzZDM2OWNmZjY3N2RjZjRhZjdiYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MPaZdtjPqiAt7OMnsEL9bS8Z5KbrGk8T9SI39uzYPwE)
> 
> 😥 Hmm.... Sad

hmm, weird. Can you show me your command installation flow?
