### ISSUE TITLE
Add import excel menu for filament

### ISSUE THREAD

**Issue by sheenazien8** [lakasir/lakasir#159]
To give a simple way to add the product, we need to add an import product feature in lakasir because sometimes merchant do not want to add their product one by one, this is the table we need to handle:

| Category | Name          | SKU    | Stock | Non Stock    | Type            | Unit | Expired | Barcode |
|----------|---------------|--------|-------|--------------|-----------------|------|----|------|
| Food     | Fried Chicken | FC0001 | 10    | Yes/No/Blank | product/service | pcs  | YYYY-m-d|0000000|
| Driink   | Ice Tea       | IT0001 | 10    | Yes/No/Blank | product/service | pcs  | YYYY-m-d|111111111|

What we have to:

1. add the export feature to download that example sheet; we can use CSV/xlsx
2. create the upload feature to import that updated example sheet

**Comment by Raza9798** [comment]
i can do this

**Comment by sheenazien8** [comment]
@Raza9798 thanks, ensure the import feature is not using the prebuilt of filament

**Comment by Raza9798** [comment]
can I integrate excel import package that I personally use for my projects

**Comment by sheenazien8** [comment]
sure @Raza9798
