### ISSUE TITLE
Only the first product can be added to the shopping list

### ISSUE THREAD

**Issue by hidjrahs** [lakasir/lakasir#198]
I tried deploying at https://lakasir.klikweb.my.id/

use default user

**Comment by sheenazien8** [comment]
@hidjrahs how i can reproduce error that you encounter?

**Comment by hidjrahs** [comment]
@sheenazien8 no error message, but If add product 2 then product 1 will go into  basket

**Comment by sheenazien8** [comment]
I didn't find the bug that you encounter on my local @hidjrahs 

https://github.com/lakasir/lakasir/assets/37477023/f0c23a87-6211-484c-97b3-b4708ec27f35

**Comment by hidjrahs** [comment]
@sheenazien8 already fix after pull and view:clear
