### ISSUE TITLE
Wrong calculate when pay in cashier,  use key pad to entry amount money

### ISSUE THREAD

**Issue by pandigresik** [lakasir/lakasir#202]
System wrong calculate amount payment because separator number using dot (.) when click in keypad

[Screencast from 08-08-24 06:49:13.webm](https://github.com/user-attachments/assets/1f8cf05d-ed0a-4327-b700-1ec6861b9207)

**Comment by muhamiyan** [comment]
@pandigresik the latest version:

<img width="864" alt="image" src="https://github.com/user-attachments/assets/d50a57a4-5529-4123-8dd3-1bdec1cc66b9">

**Comment by sheenazien8** [comment]
@pandigresik thanks, I'll check it then

**Comment by sheenazien8** [comment]
@pandigresik i didn't find the error that you found, can you reproduce it again after pull the updated version in another issues?

i'll close this issue
