### ISSUE TITLE
i get error when i run the app

### ISSUE THREAD

**Issue by delriko** [lakasir/lakasir#260]
i try to run the app directly i get this error
Symfony \ Component \ HttpKernel \ Exception \ MethodNotAllowedHttpException
The POST method is not supported for route member/login. Supported methods: GET, HEAD.

but where i run php artisan serve every thing going well

**Comment by sheenazien8** [comment]
it's strange, maybe you can give me the screen record when you open the app

**Comment by delriko** [comment]
Okay

**Comment by delriko** [comment]
you can see the video records

https://github.com/user-attachments/assets/5ff40485-2b6e-4889-ba2d-a538267af689

https://github.com/user-attachments/assets/28905d39-be51-4851-8178-f8ac4f847133

https://github.com/user-attachments/assets/b2dc5f46-afd0-47d2-b2ce-05926fc08d7b

**Comment by sheenazien8** [comment]
I think the filament did not work properly on xampp, you can check it on filament github repository

I've found this https://github.com/filamentphp/filament/discussions/12964, the problem was because the `/public` in URL

**Comment by sheenazien8** [comment]
I'll close this issue because I think it's related to filament behavior
