### ISSUE TITLE
Show Calculate Total In Create Purchase Transaction

### ISSUE THREAD

**Issue by sheenazien8** [lakasir/lakasir#43]
![Screenshot from 2020-08-15 07-00-22](https://user-images.githubusercontent.com/37477023/90300527-04e10200-dec5-11ea-954c-c734ecebf803.png)

Jumlahkan total pengeluaran pembelanjaan di kolom total pojok kanan bawah.

**Comment by gaweki** [comment]
halo mas @sheenazien8 , cara ini loginnya gimana?

**Comment by sheenazien8** [comment]
@gaweki terimakasih mas udah mau clone, mungkin port atau hostnya salah mas, cobak di ganti atau install manual mas, bisa di migrate lewat cli mas

**Comment by gaweki** [comment]
apa ada akun  telegram mas? untuk panduin install

**Comment by sheenazien8** [comment]
@gaweki ada mas, ini linknya https://t.me/sheenazien
