### ISSUE TITLE
[new item] can post negative number

### ISSUE THREAD

**Issue by lakuapik** [lakasir/lakasir#58]
saya tertarik dengan projek ini, pas saya cek masih ada beberapa bug. salah satunya ini:

* bisa input negatif number, dan validasinya centang

![Peek 2020-10-02 16-46](https://user-images.githubusercontent.com/20186786/94910575-1b700680-04cf-11eb-9707-7e0ed7aa7de1.gif)

sekalian tanya, ini masih dilanjut gak ya projeknya?

**Comment by sheenazien8** [comment]
@lakuapik iya mas masih, untuk sementara saya ingin bisa sampe realese v1.0-beta mas

**Comment by lakuapik** [comment]
wah mantapp, yg kurang2 apa nih mas? siapa tahu bisa bantu wkwk

**Comment by sheenazien8** [comment]
@lakuapik check di ideas mas, di readme nya, sudah aku tulis beberapa mas
