### ISSUE TITLE
error failed to install because host only accept alphadash

### ISSUE THREAD

**Issue by alifrizkip** [lakasir/lakasir#60]
[
![Screenshot from 2020-10-03 22-19-51](https://user-images.githubusercontent.com/18460240/94995351-eb585e80-05c7-11eb-90cc-36128fd81b77.png)
](url)

**Comment by alifrizkip** [comment]
PR #61

**Comment by sheenazien8** [comment]
@alifrizkip thanks for PR, I missed it
