### ISSUE TITLE
Submit Button not working on forms

### ISSUE THREAD

**Issue by muffaddal** [lakasir/lakasir#66]
Hi, Thanks for the awesome POS system. I was trying to set up and do some testing, but cant move ahead from login page. The installation and Database set up is all done correctly. On form submit for login, it does not work! I don't see anything in the network tab. 

Upon debugging I figured the button component with type submit does not work. It works well if I use a simple input type submit on forms. Please help!

Thanks,
Mufaddal.
![Screenshot from 2020-10-12 07-56-55](https://user-images.githubusercontent.com/5665522/95698863-8a342900-0c60-11eb-8690-db2f5208f310.png)

**Comment by sheenazien8** [comment]
@muffaddal, maybe you can swtich from build in server in laravel to laravel valet for development server, if this solution still doesn't solve the problem, I'll go through the case.

Thank you for using Lakasir.

**Comment by aqmalio** [comment]
hi @muffaddal, can i try to solve the problem ?
i would like to work on this

**Comment by sheenazien8** [comment]
@aqmalio yes you can, i suggest this problem because the browser is used, if i use firefox lakasir can running well, but if i use chrome button didn't work, 

I am very grateful if you would like to contribute to this project.

**Comment by mufaddalnagpurwala** [comment]
@aqmalio Your solutions works! Thanks!

**Comment by swalayan-hasbuna** [comment]
i have same problem.. how to fix it.. what the default username and password?

**Comment by swalayan-hasbuna** [comment]
if you want to integrate this repo with whatsapp gateway for payment/ bill notification etc .. i have source code for that..
