### ISSUE TITLE
The profile page is not working

### ISSUE THREAD

**Issue by aqmalio** [lakasir/lakasir#73]
![image](https://user-images.githubusercontent.com/33825185/97115387-134f6380-1729-11eb-9117-cd608b0bee66.png)

This is bug or feature in progress ?

Thanks

**Comment by dabayuaji** [comment]
@aqmalio maybe bug, because in my machine this page working well

**Comment by sheenazien8** [comment]
@aqmalio maybe bug, because in my machine this page working well, or maybe vue blade in lakasir on chrome browser can't running well
