### ISSUE TITLE
[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders when I try to log in

### ISSUE THREAD

**Issue by hashan-athu** [lakasir/lakasir#75]
I have installed and configured successfully. After I try to login using my credentials the submit button keep loading and nothing happens. So I inspected and I Got this,
"app.js:96477 [Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "loading"
found in
---> <Button> at resources/js/components/Button/Button.vue
       <Root>

warn | @ | app.js:96477
  | (anonymous) | @ | app.js:100520
  | reactiveSetter | @ | app.js:96903
  | proxySetter | @ | app.js:100473
  | clicked | @ | app.js:2010
  | invokeWithErrorHandling | @ | app.js:97706
  | invoker | @ | app.js:98031
  | original._wrapper | @ | app.js:103390
"
![Screenshot 2020-12-21 13:15:39](https://user-images.githubusercontent.com/7894661/102751971-d3a2a200-438e-11eb-9d6b-c123995a4da6.png)

**Comment by sheenazien8** [comment]
@blackeaglehdc yes lakasir only runwell in firefox browser, and can't run in chrome, this issue will be maintened soon in february, I plan to rewrite all the compnents of the video to the livewire. thanks for the issue
