### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by MusheAbdulHakim** [lakasir/lakasir#94]
I used `composer create-project lakasir/lakasir your-project-name`  to install the project and i have followed the installer to do the installation but after the installer is completed, i can't login .
After entering my credentials, the button just be hanging and loading.It will not come

**Comment by ykslo** [comment]
same on me

**Comment by MusheAbdulHakim** [comment]
I don't know if this repository has been abandoned. Even if they didn't have the time to solve this , if the owner could just explain what's wrong, some of us will have written a fix for it.But there hasn't been any replies

**Comment by sheenazien8** [comment]
@ykslo @MusheAbdulHakim sorry for late response and not reply your question, for now lakasir is full under development again, because there are so many problems found, I'm sorry that as the owner of the lakasir can't give a direct answer as a temporary solution, I'm sorry.

**Comment by N34R** [comment]
@MusheAbdulHakim @ykslo It can install with
1. `composer create-project lakasir/lakasir your-project-name`.
2. After that copy `.env.example` to `.env` and setup database inside `.env` file.
3. Run the following command `php artisan migrate; php artisan passport:install;`
4. Then `npm install` don't run `npm run dev`.

**Comment by N34R** [comment]
When i clone this repo from github. and run `composer install`. It will throw [runtimeException] Source path "../packages/livewire-components" is not found for package sheenazien8/livewire-components

**Comment by JustJeremy** [comment]
Yeah, I'd say this project is all but dead now.
I just tried to do the install and it barfed.  Doing an npm update there were 139 vulnerabilities. 66 moderate, 58 high, and 12 critical.  Trying to do a fix for that fixed 99 vulnerabilities.  However, the fixes involved several breaking changes.  Others are deprecated and no longer maintained. 
Kind of a bummer as I thought this might have some potential.
